name: Deployer
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: build and deploys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app and Storybook and prepare for deployment
        run: yarn predeploy
        env:
          GA_TRACKING_ID: UA-332655-6

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
