name: Deployer
on:
  push:
    branches:
      - master

env:
  FORCE_COLOR: 3

jobs:
  deploy:
    name: build and deploys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint source
        run: pnpm lint

      - name: Build app and generate PDF
        run: pnpm predeploy
        env:
          PUBLIC_POSTHOG_PROJECT_API_KEY: ${{ vars.PUBLIC_POSTHOG_PROJECT_API_KEY }}

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
